import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {numeric,normalizeRelease} from '../lib/economic-provider.mjs';
import economic from '../api/economic.js';
const response=()=>({code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(d){this.data=d;return this;}});
test('numeric values preserve missing versus zero and magnitude',()=>{assert.equal(numeric('0.0%'),0);assert.equal(numeric('—'),null);assert.equal(numeric(null),null);assert.equal(numeric('1.2M'),1200000);assert.equal(numeric('-200K'),-200000);assert.equal(numeric('inflation rose 3%'),null);});
test('release dates are UTC; previous revision is not current actual',()=>{const e=normalizeRelease({Date:'2026-10-02T12:30:00',Actual:'178K',Forecast:'175K',Previous:'142K',Revised:'161K',Reference:'Sep',ReferenceDate:'2026-09-01T00:00:00',LastUpdate:'2026-10-02T12:31:00'});assert.equal(e.releaseDate,'2026-10-02T12:30:00.000Z');assert.equal(e.actual,178000);assert.equal(e.previous,142000);assert.equal(e.priorBeforeRevision,161000);assert.equal(e.surprise,3000);assert.equal(e.reference,'Sep');assert.equal(normalizeRelease({Date:'invalid'}),null);});
test('missing configured provider returns explicit unavailable response',async()=>{const key=process.env.TRADING_ECONOMICS_KEY;delete process.env.TRADING_ECONOMICS_KEY;try{const res=response();await economic({query:{currency:'USD',months:'6'}},res);assert.equal(res.code,503);assert.equal(res.data.mode,'not-configured');assert.deepEqual(res.data.events,[]);assert.equal(res.data.sourceUpdatedAt,null);}finally{if(key)process.env.TRADING_ECONOMICS_KEY=key;}});
test('economic endpoint validates queries',async()=>{const res=response();await economic({query:{currency:'XXX',months:'6'}},res);assert.equal(res.code,400);});
const ctx={Date,AbortController,setTimeout,clearTimeout,fetch:()=>{},process};vm.createContext(ctx);vm.runInContext(fs.readFileSync('api/rates.js','utf8').replace('export default async function','async function'),ctx);
test('rates accept markdown fixture, reject invalid probability totals',()=>{const source=fs.readFileSync('tests/fixtures/rates-source.txt','utf8'),clean=ctx.cleanText(source),bank={name:'Federal Reserve'};const block=ctx.bankSection(clean,bank,0),p=ctx.parseProbabilities(block);assert.ok(p);assert.equal(p.hike,19.5);assert.equal(p.hold,80.5);assert.equal(ctx.parseProbabilities('Rate Hike 90% Hold 90% Rate Cut 1%'),null);assert.equal(ctx.parseSourceDate(clean),'2026-10-06T00:00:00.000Z');});
const html=fs.readFileSync('index.html','utf8'),inline=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)];
test('main terminal inline scripts all parse',()=>{for(const x of inline)new vm.Script(x[1]);});
test('monthly coverage cannot be mislabeled quarterly',()=>{const a=html.slice(html.indexOf('function observationMonthKey'),html.indexOf('function freshnessInfo'));vm.runInContext(a,ctx);const c=ctx.coverageInfo([['2026-08',1],['2026-09',2]],'claims');assert.equal(c.required,6);assert.equal(c.complete,false);});
test('null rates do not display 0%',()=>{const a=html.slice(html.indexOf('function rateProbFmt'),html.indexOf('function rateSnapshot'));vm.runInContext(a,ctx);assert.equal(ctx.rateProbFmt(null),'—');assert.equal(ctx.rateProbFmt(0),'0.00%');assert.deepEqual(JSON.parse(JSON.stringify(ctx.rateValues([{rate:'2%',latest:null}],'latest'))),{});});
test('bank sections never borrow another bank probabilities',()=>{const source=ctx.cleanText(fs.readFileSync('tests/fixtures/rates-source.txt','utf8'));const boj=ctx.parseProbabilities(ctx.bankSection(source,{name:'Bank of Japan'}));assert.equal(boj.hike,0);assert.equal(boj.hold,95.1);assert.equal(ctx.parseProbabilities(ctx.bankSection(source,{name:'Reserve Bank of New Zealand'})),null);assert.equal(ctx.bankSection(source,{name:'Bank of Canada'}),'');});
test('verified snapshot has traceable, non-future observations and honest coverage totals',()=>{const d=JSON.parse(fs.readFileSync('assets/economic-archive.json')),rows=Object.values(d.currencies).flat(),verified=rows.filter(x=>x.verificationStatus==='verified-primary');assert.equal(d.audit.verified,verified.length);assert.equal(d.audit.total,rows.length);const keys=new Set();for(const x of verified){assert.ok(Number.isFinite(x.actual));assert.equal(new URL(x.sourceUrl).protocol,'https:');assert.ok(Date.parse(x.verifiedAt)<=Date.now());if(x.releaseDate)assert.ok(Date.parse(x.releaseDate)<=Date.now());assert.equal(x.forecast,null,'primary statistics do not supply verified market consensus');const key=[x.event,x.reference,x.source].join('|');assert.ok(!keys.has(key),key);keys.add(key)}for(const [c,rr] of Object.entries(d.currencies))assert.ok(rr.some(x=>x.verificationStatus==='verified-primary'&&/GDP/.test(x.event)),c+' GDP coverage');});
test('reviewed calendar actuals preserve forecasts without claiming consensus verification',()=>{const context={Date,Intl,console,AbortSignal,process,setTimeout,clearTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync('api/calendar.js','utf8').replace('export default async function','async function'),context);const result=context.applyPrimaryActuals([{date:'2026-10-07T01:30:00+02:00',currency:'JPY',event:'Labor Cash Earnings y/y',actual:'—',forecast:'3.3%',previous:'2.4%'}])[0];assert.equal(result.actual,'3.8%');assert.equal(result.forecast,'3.3%');assert.equal(result.verificationStatus,'verified-primary');assert.equal(result.forecastVerificationStatus,'provider-unverified');});

test('blank and future releases cannot create trading catalysts',()=>{const h=fs.readFileSync('index.html','utf8'),c={Date,liveEvents:[{date:'2099-01-01',actual:'100K',forecast:'50K'},{date:'2026-10-07T01:00:00Z',actual:'—',forecast:'90K'}],catalystKind:()=> 'NFP',catalystWeight:()=>3};vm.createContext(c);vm.runInContext(h.slice(h.indexOf('function num(v)'),h.indexOf('function inferSurprise')),c);vm.runInContext(h.slice(h.indexOf('function scoredLiveEvents()'),h.indexOf('function canonicalCatalystEvent')),c);assert.ok(Number.isNaN(c.num('—')));assert.ok(Number.isNaN(c.num('')));assert.equal(c.num('1.2M'),1200000);assert.equal(c.num('0.0%'),0);assert.equal(c.scoredLiveEvents().length,0);});

test('history window includes midnight on its first day',()=>{const js=fs.readFileSync('assets/economic-data.js','utf8'),FakeDate=class extends Date{constructor(...args){super(...(args.length?args:['2026-10-07T19:00:00Z']))}},c={Date:FakeDate,state:{months:6,events:[{event:'CPI',actual:3,referenceDate:'2026-04-01T00:00:00Z'}]},matches:()=>true};vm.createContext(c);vm.runInContext(js.slice(js.indexOf('function visible()'),js.indexOf('function render()')),c);assert.equal(c.visible().length,1);});
