from pathlib import Path
import re

src=Path('index.html')
text=src.read_text()
if 'G10 Macro Monitor · 3M Base + Live Catalysts' in text:
    print('Already upgraded'); raise SystemExit(0)

css_anchor='.newsitem{padding:9px 10px;border-bottom:1px solid #1d1d1d}.newsitem:hover{background:#111}'
css_add='''.newsitem{padding:9px 10px;border-bottom:1px solid #1d1d1d;position:relative}.newsitem:hover{background:#111}.newsitem.high-impact{border-left:3px solid var(--red);background:linear-gradient(90deg,rgba(255,95,87,.16),rgba(255,95,87,.035) 62%,transparent);box-shadow:inset 0 0 22px rgba(255,95,87,.08);animation:highImpactPulse 2.4s ease-in-out infinite}.newsitem.high-impact a{color:#fff}.highflag{color:var(--red);font-size:8.5px;font-weight:900;letter-spacing:.65px;text-transform:uppercase;margin-left:7px}.macroflag{color:var(--accent2);font-size:8.5px;font-weight:900;margin-left:7px}.live-score{font-size:11px;font-weight:900;white-space:nowrap}.live-score.pos{color:var(--green)}.live-score.neg{color:var(--red)}.live-score.flat{color:var(--amber)}.catalyst-panel{max-height:620px;overflow:auto}.catalyst-row{padding:10px;border-bottom:1px solid #1d1d1d;background:#080808}.catalyst-row:last-child{border-bottom:0}.catalyst-row.high{border-left:3px solid var(--red);background:rgba(255,95,87,.055)}@keyframes highImpactPulse{0%,100%{box-shadow:inset 0 0 18px rgba(255,95,87,.06),0 0 0 rgba(255,95,87,0)}50%{box-shadow:inset 0 0 28px rgba(255,95,87,.12),0 0 12px rgba(255,95,87,.12)}}'''
if css_anchor not in text: raise SystemExit('CSS anchor not found')
text=text.replace(css_anchor, css_add, 1)

old_state="const ORDER=Object.keys(RES).sort((a,b)=>RES[a].order-RES[b].order);\nlet liveEvents=[]; let sourceMode='seed'; let newsData={financialjuice:[],reuters:[],reutersConfigured:false}; let newsMode='loading'; let alertsEnabled=localStorage.getItem('tl_alerts')==='1';"
new_state="""const ORDER=Object.keys(RES).sort((a,b)=>RES[a].order-RES[b].order); // immutable 3M base order
let liveEvents=[]; let sourceMode='seed'; let newsData={financialjuice:[],macroUpdates:[],reuters:[],reutersConfigured:false}; let newsMode='loading'; let alertsEnabled=localStorage.getItem('tl_alerts')==='1';
function catalystScore(c){let seen=new Set(),sum=0;for(const u of (newsData.macroUpdates||[])){if(u.ccy!==c)continue;let k=[u.date,u.event,u.actual].join('|');if(seen.has(k))continue;seen.add(k);sum+=Number(u.score||0)}return Math.max(-4,Math.min(4,Math.round(sum*10)/10))}
function liveStrength(c){return (11-Number(RES[c].order||10)) + catalystScore(c)*.70}
function currentOrder(){return [...ORDER].sort((a,b)=>liveStrength(b)-liveStrength(a)||RES[a].order-RES[b].order)}
function scoreMarkup(c){let s=catalystScore(c),cls=s>0?'pos':s<0?'neg':'flat';return `<span class=\"live-score ${cls}\">${s>0?'+':''}${s.toFixed(1)}</span>`}
function newsMacroFor(c){return (newsData.macroUpdates||[]).filter(x=>x.ccy===c).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0))[0]||null}
function adjustedBiasNote(c){let s=catalystScore(c);return s>=3?'UPGRADE WATCH':s<=-3?'DOWNGRADE WATCH':Math.abs(s)>=1.5?'CATALYST ACTIVE':'BASE INTACT'}"""
if old_state not in text: raise SystemExit('state anchor not found')
text=text.replace(old_state,new_state,1)

old_latest="function latestFor(c){let xs=liveEvents.filter(x=>x.currency===c && x.actual && x.actual!=='—').sort((a,b)=>new Date(b.date)-new Date(a.date));if(xs[0])return xs[0];let r=STATIC_RELEASES.find(x=>x[1]===c);return r?{date:r[0],currency:r[1],event:r[2],previous:r[3],forecast:r[4],actual:r[5],label:r[6],impact:r[7],why:r[8]}:null}"
new_latest="function latestFor(c){let nm=newsMacroFor(c);if(nm)return {date:nm.date,currency:nm.ccy,event:nm.event,previous:nm.previous,forecast:nm.forecast,actual:nm.actual,label:nm.result,impact:Number(nm.score)>0?'Strengthens':Number(nm.score)<0?'Weakens':'Neutral',why:nm.why,score:nm.score,highImpact:nm.highImpact};let xs=liveEvents.filter(x=>x.currency===c && x.actual && x.actual!=='—').sort((a,b)=>new Date(b.date)-new Date(a.date));if(xs[0])return xs[0];let r=STATIC_RELEASES.find(x=>x[1]===c);return r?{date:r[0],currency:r[1],event:r[2],previous:r[3],forecast:r[4],actual:r[5],label:r[6],impact:r[7],why:r[8]}:null}"
if old_latest not in text: raise SystemExit('latestFor anchor not found')
text=text.replace(old_latest,new_latest,1)

start=text.index('function table(){'); end=text.index('function overview(){', start)
new_table="""function table(){let order=currentOrder();return `<div class=\"card\"><div class=\"monitor-head\"><h3>G10 Macro Monitor · 3M Base + Live Catalysts</h3><div class=\"monitor-legend\">LIVE Δ IS WEIGHTED FROM STRUCTURED FINANCIALJUICE ACTUAL / FORECAST / PREVIOUS RELEASES</div></div><div class=\"tablewrap compact-table\"><table><thead><tr><th>Rank</th><th>CCY</th><th>3M Macro</th><th>Central Bank</th><th>Inflation</th><th>Labor</th><th>2Y / Pricing</th><th>Latest Catalyst</th><th>Live Δ</th><th>Bias</th></tr></thead><tbody>${order.map((c,i)=>{let r=RES[c],lc=latestFor(c),s=catalystScore(c);return `<tr onclick=\"openDrawer('${c}')\" style=\"cursor:pointer\"><td class=\"ranknum\">${String(i+1).padStart(2,'0')}</td><td><div class=\"ccy-main\">${c}</div><div class=\"mini\">Base #${r.order} · ${esc(r.country)}</div></td><td class=\"macro-cell\">${tag(r.macro,r.macroTone)}<div class=\"mini\">${esc(r.growth)} · ${esc(r.activity)}</div></td><td class=\"policy-cell\">${tag(r.cb,r.cbTone)}<div class=\"mini\">${esc(r.rate)} · ${esc(r.next)}</div></td><td>${tag(r.inflation,r.inflTone)}<div class=\"mini\">${esc(r.core)} · tgt ${esc(r.target)}</div></td><td>${tag(r.labor,r.laborTone)}</td><td class=\"yield-cell\"><b>${esc(r.y2)}</b><div class=\"mini\">${esc(r.pricing)}</div></td><td class=\"catalyst-cell\">${catalystLabel(lc)}<div class=\"mini\" style=\"margin-top:4px\">${lc?esc(lc.event)+' · '+esc(lc.actual)+' vs '+esc(lc.forecast):'—'}</div></td><td>${scoreMarkup(c)}<div class=\"mini\">${adjustedBiasNote(c)}</div></td><td class=\"bias-cell\">${tag(r.final,r.tone)}<div class=\"mini\">CONF ${esc(r.confidence)}</div></td></tr>`}).join('')}</tbody></table></div><div class=\"mini\" style=\"margin-top:7px\">BASE = 3M macro / policy state. LIVE Δ = short-term catalyst value only. High-impact releases carry more weight; neutral/in-line = 0. A single print can move the ranking, but it does not automatically overwrite the underlying 3M bias.</div></div>`}
"""
text=text[:start]+new_table+text[end:]

text=text.replace("function overview(){let top=ORDER.slice(0,3),low=ORDER.slice(-3).reverse();let fresh=[...ORDER].map(c=>latestFor(c))", "function overview(){let order=currentOrder(),top=order.slice(0,3),low=order.slice(-3).reverse();let fresh=[...order].map(c=>latestFor(c))",1)
text=text.replace("#${ORDER.length-i}", "#${currentOrder().length-i}")
text=text.replace("${ORDER.length-i}</div>", "${currentOrder().length-i}</div>")

news_start=text.index('function newsCardItem('); news_end=text.index('function showToast(', news_start)
new_news="""function newsCardItem(x,src){let title=esc(x.title||'Untitled'),url=esc(x.link||x.url||'#'),tm=esc(x.time||x.pubDate||''),hi=!!x.highImpact,macro=!!x.macro;return `<div class=\"newsitem ${hi?'high-impact':''}\"><a href=\"${url}\" target=\"_blank\" rel=\"noopener\">${hi?'<span class=\"breaking\">● </span>':''}${title}</a>${hi?'<span class=\"highflag\">HIGH IMPACT</span>':''}${macro?'<span class=\"macroflag\">G10 CATALYST</span>':''}<div class=\"newsmeta\"><span class=\"sourcebadge fj\">${esc(src)}</span>${tm?`<span>${tm}</span>`:''}</div></div>`}
function catalystRow(u){let s=Number(u.score||0),cls=s>0?'good':s<0?'bad':'warn';return `<div class=\"catalyst-row ${u.highImpact?'high':''}\"><div style=\"display:flex;justify-content:space-between;gap:8px\"><b>${esc(u.ccy)} · ${esc(u.event)}</b><span class=\"${cls}\">${s>0?'+':''}${s.toFixed(1)}</span></div><div class=\"mini\" style=\"margin-top:5px\">Actual ${esc(u.actual)} · Forecast ${esc(u.forecast)} · Previous ${esc(u.previous)} · ${esc(u.result)}</div></div>`}
function newsDesk(){let fj=newsData.financialjuice||[],mu=newsData.macroUpdates||[];$('#news').innerHTML=`<div class=\"livebar\"><div><b>FinancialJuice · Live Headlines</b><div class=\"statusline\">Auto refresh: 60s · high-impact macro / regime changes glow red</div></div><button class=\"refresh\" onclick=\"loadNews(true)\">Refresh now</button></div><div class=\"newsgrid\"><div class=\"newspanel\"><div class=\"newshead\"><b>Headline Feed</b><span class=\"tag ${newsMode==='live'?'green':'amber'}\">${newsMode==='live'?'LIVE':'CONNECTING'}</span></div><div class=\"newslist\">${fj.length?fj.slice(0,80).map(x=>newsCardItem(x,'FinancialJuice')).join(''):'<div class=\"newsitem mini\">Feed loading or temporarily rate-limited.</div>'}</div></div><div class=\"newspanel\"><div class=\"newshead\"><b>G10 · Live Macro Catalysts</b><span class=\"tag green\">AUTO RANK</span></div><div class=\"catalyst-panel\">${mu.length?mu.slice(0,25).map(catalystRow).join(''):'<div class=\"newsitem mini\">Waiting for a structured Actual / Forecast / Previous macro release.</div>'}</div></div></div><div class=\"card\" style=\"margin-top:10px\"><div class=\"call\"><b>Rule:</b> ordinary headlines stay headlines only. A structured G10 release is scored as Beat / Miss / Neutral with event-specific weight. CPI/PCE/NFP/rate decisions carry the most weight; secondary data carry less. The live value can re-rank G10, while the 3M macro state remains the base thesis.</div></div>`}
"""
text=text[:news_start]+new_news+text[news_end:]

old_detect=re.search(r"function detectFJMacro\(items\)\{.*?\}\nasync function loadNews\(manual=false\)\{.*?\}\n", text, re.S)
if not old_detect: raise SystemExit('detect/load news block not found')
new_detect="""function detectFJMacro(items){let seen={};try{seen=JSON.parse(localStorage.getItem('tl_fj_seen')||'{}')}catch(e){};let changed=false;for(const x of items||[]){if(!x.macro)continue;let key=x.guid||x.link||x.url||x.title;if(seen[key])continue;seen[key]=1;changed=true;let m=x.macro,body=`${m.ccy} ${m.event}: ${m.actual} vs ${m.forecast} · ${m.result} · live value ${Number(m.score)>0?'+':''}${Number(m.score||0).toFixed(1)}`;showToast(x.highImpact?'HIGH-IMPACT MACRO':'MACRO RELEASE',body,x.highImpact?'release-alert':'result-alert');browserNotify('TradingLab · Macro Catalyst',body,key)}if(changed)localStorage.setItem('tl_fj_seen',JSON.stringify(seen))}
async function loadNews(manual=false){try{let r=await fetch('/api/news',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);let d=await r.json();newsData={financialjuice:d.items||d.financialjuice||[],macroUpdates:d.macroUpdates||[],reuters:d.reuters||[],reutersConfigured:!!d.reutersConfigured};newsMode=d.financialJuiceLive||d.mode==='live'?'live':'degraded';detectFJMacro(newsData.financialjuice);render()}catch(e){newsMode='error';if(manual)showToast('News feed error',String(e.message||e));newsDesk()}}
"""
text=text[:old_detect.start()]+new_detect+text[old_detect.end():]

text=text.replace("function divergence(){let pairs=[];for(let i=0;i<3;i++)pairs.push([ORDER[i],ORDER[ORDER.length-1-i]]);", "function divergence(){let order=currentOrder(),pairs=[];for(let i=0;i<3;i++)pairs.push([order[i],order[order.length-1-i]]);",1)

old_draw="['Confidence',r.confidence],['Weekly Focus',r.weekly],['Invalidation',r.invalidate],['Latest Catalyst',lc?`${lc.event}: ${lc.actual} vs ${lc.forecast} · ${lc.impact||lc.label||'Update'}`:'—']"
new_draw="['Confidence',r.confidence],['Live Catalyst Value',`${catalystScore(c)>0?'+':''}${catalystScore(c).toFixed(1)} · ${adjustedBiasNote(c)}`],['Weekly Focus',r.weekly],['Invalidation',r.invalidate],['Latest Catalyst',lc?`${lc.event}: ${lc.actual} vs ${lc.forecast} · ${lc.impact||lc.label||'Update'}`:'—']"
if old_draw in text: text=text.replace(old_draw,new_draw,1)

text=text.replace("<b>Data base updated 30 Aug 2026.</b> Primary macro inputs use official statistics / central-bank releases; market consensus and pricing are cross-checked with Reuters. The browser calls <b>/api/calendar</b> every 30 seconds. If a TradingEconomics credential is configured on the server, new G10 releases are returned live. If no provider key exists, the terminal stays in <b>seed mode</b> and never pretends that stale data is live.", "<b>3M base + FinancialJuice catalyst layer.</b> FinancialJuice headlines refresh every 60 seconds. Ordinary headlines never overwrite macro data. Only structured G10 releases with Actual / Forecast / Previous receive a Beat / Miss / Neutral catalyst value and can re-rank the live G10 table. High-impact macro / policy / regime headlines glow red. The underlying 3M macro state remains the base thesis.",1)
text=text.replace("live macro layer refreshes every 30 seconds when a provider is connected.", "FinancialJuice headlines refresh every 60 seconds · structured macro catalysts can re-rank G10 live.",1)

src.write_text(text)
print('Updated index.html',len(text.encode()),'bytes')
