const FJ_RSS='https://www.financialjuice.com/feed.ashx?xy=rss';
const CCY_PATTERNS=[['EUR',/\b(euro area|eurozone|euro zone|european central bank|ecb)\b/i],['GBP',/\b(united kingdom|u\.?k\.?|britain|british|bank of england|boe)\b/i],['JPY',/\b(japan|japanese|bank of japan|boj)\b/i],['CHF',/\b(switzerland|swiss|swiss national bank|snb)\b/i],['AUD',/\b(australia|australian|reserve bank of australia|rba)\b/i],['NZD',/\b(new zealand|reserve bank of new zealand|rbnz)\b/i],['CAD',/\b(canada|canadian|bank of canada|boc)\b/i],['SEK',/\b(sweden|swedish|riksbank)\b/i],['NOK',/\b(norway|norwegian|norges bank)\b/i],['USD',/\b(united states|u\.?s\.?|federal reserve|fed|fomc)\b/i]];
function text(v=''){return String(v).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function tag(block,name){let m=block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return m?text(m[1]):''}
function tags(block,name){return [...block.matchAll(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'gi'))].map(m=>text(m[1])).filter(Boolean)}
function detectCcy(title=''){for(const [ccy,re] of CCY_PATTERNS)if(re.test(title))return ccy;return''}
function categories(title=''){let s=title.toLowerCase(),o=[];if(/\b(fed|fomc|ecb|boe|boj|rba|rbnz|boc|snb|riksbank|norges bank|central bank|interest rate|rate decision)\b/.test(s))o.push('CENTRAL BANK');if(/\b(cpi|pce|inflation|nfp|payroll|unemployment|employment|wage|jobs|jolts|gdp|pmi|ism|retail sales|industrial production|jobless|claims|economic|consumer confidence|trade balance)\b/.test(s))o.push('MACRO');if(/\b(oil|crude|brent|wti|gas|opec|energy)\b/.test(s))o.push('ENERGY');if(/\b(war|attack|missile|iran|russia|ukraine|china|tariff|sanction|geopolit)\b/.test(s))o.push('GEOPOLITICS');if(/\b(stock|equities|s&p|nasdaq|dow|earnings)\b/.test(s))o.push('EQUITIES');return [...new Set(o)]}
function parseVal(raw){if(raw==null)return null;let s=String(raw).replace(/,/g,'').trim(),m=s.match(/[-+]?\d*\.?\d+/);if(!m)return null;let n=Number(m[0]);if(!Number.isFinite(n))return null;let tail=s.slice(m.index+m[0].length).trim().toLowerCase();if(/^k\b/.test(tail))n*=1e3;else if(/^m\b/.test(tail))n*=1e6;else if(/^b\b/.test(tail))n*=1e9;return n}
function capture(title,label){let p=[new RegExp(`${label}\\s*[:=]?\\s*([-+]?\\d[\\d,.]*\\s*(?:%|k|m|b)?)`,'i'),new RegExp(`${label}[^0-9+\\-]{0,16}([-+]?\\d[\\d,.]*\\s*(?:%|k|m|b)?)`,'i')];for(const r of p){let m=title.match(r);if(m)return m[1].trim().replace(/[),;]+$/,'')}return null}
function eventName(title=''){let s=title.replace(/^FinancialJuice\s*:\s*/i,'').replace(/\bActual\b[\s\S]*$/i,'').replace(/\s*[-–—:]\s*$/,'').trim();s=s.replace(/^(United States|U\.?S\.?|US|Euro Area|Eurozone|Euro Zone|United Kingdom|U\.?K\.?|UK|Britain|Japan|Switzerland|Australia|New Zealand|Canada|Sweden|Norway|Federal Reserve|Fed|FOMC|European Central Bank|ECB|Bank of England|BoE|Bank of Japan|BoJ|Swiss National Bank|SNB|Reserve Bank of Australia|RBA|Reserve Bank of New Zealand|RBNZ|Bank of Canada|BoC|Riksbank|Norges Bank)\s*[-–—:]?\s*/i,'');return s.trim()||title.slice(0,110)}
function eventInfo(title=''){let s=title.toLowerCase();if(/core.*(cpi|pce)|trimmed mean|median cpi|cpif/.test(s))return{kind:'CORE INFLATION',weight:3,lowerBetter:false};if(/\b(cpi|pce|inflation rate|hicp)\b/.test(s))return{kind:'INFLATION',weight:2.5,lowerBetter:false};if(/non.?farm|\bnfp\b|payrolls?/.test(s))return{kind:'NFP',weight:3,lowerBetter:false};if(/unemployment rate/.test(s))return{kind:'UNEMPLOYMENT',weight:2.75,lowerBetter:true};if(/average hourly|wage|earnings growth/.test(s))return{kind:'WAGES',weight:2.25,lowerBetter:false};if(/interest rate|rate decision|policy rate|cash rate|bank rate/.test(s))return{kind:'RATE',weight:3,lowerBetter:false};if(/ism.*services|services.*ism/.test(s))return{kind:'ISM SERVICES',weight:2.25,lowerBetter:false};if(/ism.*manufacturing|manufacturing.*ism/.test(s))return{kind:'ISM MANUFACTURING',weight:1.75,lowerBetter:false};if(/\bgdp\b/.test(s))return{kind:'GDP',weight:2,lowerBetter:false};if(/\bjolts\b|job openings/.test(s))return{kind:'JOLTS',weight:1.5,lowerBetter:false};if(/employment change|employment level/.test(s))return{kind:'EMPLOYMENT',weight:2,lowerBetter:false};if(/jobless|claims/.test(s))return{kind:'CLAIMS',weight:1.25,lowerBetter:true};if(/services pmi/.test(s))return{kind:'SERVICES PMI',weight:1.5,lowerBetter:false};if(/manufacturing pmi/.test(s))return{kind:'MANUFACTURING PMI',weight:1.25,lowerBetter:false};if(/composite pmi/.test(s))return{kind:'COMPOSITE PMI',weight:1.25,lowerBetter:false};if(/retail sales/.test(s))return{kind:'RETAIL SALES',weight:1.5,lowerBetter:false};if(/industrial production/.test(s))return{kind:'INDUSTRIAL PRODUCTION',weight:1.25,lowerBetter:false};return{kind:'MACRO',weight:1,lowerBetter:false}}
function parseMacro(title,pubDate){let ccy=detectCcy(title),actual=capture(title,'Actual'),forecast=capture(title,'Forecast'),previous=capture(title,'Previous');if(!ccy||actual==null||forecast==null||previous==null)return null;let a=parseVal(actual),f=parseVal(forecast),p=parseVal(previous);if(a==null||f==null||p==null)return null;let info=eventInfo(title),eps=Math.max(1e-12,Math.abs(f)*1e-6),raw=a-f,result=Math.abs(raw)<=eps?'NEUTRAL':(info.lowerBetter?(a<f?'BEAT':'MISS'):(a>f?'BEAT':'MISS'));let score=result==='BEAT'?info.weight:result==='MISS'?-info.weight:0;let highImpact=info.weight>=1.5;let why=result==='NEUTRAL'?'In line with consensus; no live ranking value.':info.kind.includes('INFLATION')?(score>0?'Hotter than expected → hawkish currency catalyst.':'Softer than expected → dovish currency catalyst.'):(info.kind==='RATE'?(score>0?'More hawkish than expected.':'More dovish than expected.'):(score>0?'Stronger than expected macro impulse.':'Weaker than expected macro impulse.'));return{ccy,event:eventName(title),kind:info.kind,actual,forecast,previous,result,score:Math.round(score*100)/100,weight:info.weight,highImpact,why,date:pubDate||new Date().toISOString()}}
function regimeHighImpact(title=''){let s=title.toLowerCase();return /\b(emergency|intervention|unexpected rate|surprise hike|surprise cut|rate decision|declares war|missile attack|major sanctions|default|capital controls)\b/.test(s)}
function parseRSS(xml,limit=80){return [...String(xml).matchAll(/<item\b[\s\S]*?<\/item>/gi)].slice(0,limit).map(m=>{let b=m[0],title=tag(b,'title'),pubDate=tag(b,'pubDate'),macro=parseMacro(title,pubDate),cats=[...new Set([...tags(b,'category'),...categories(title)])],highImpact=!!macro?.highImpact||regimeHighImpact(title);return {title,link:tag(b,'link'),url:tag(b,'link'),guid:tag(b,'guid'),pubDate,time:pubDate,categories:cats,highImpact,macro}}).filter(x=>x.title)}
async function fetchRSS(url,headers={}){let r=await fetch(url,{headers:{Accept:'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5','User-Agent':'TradingLabMacroTerminal/2.0',...headers}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return parseRSS(await r.text())}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=40');let items=[],reuters=[],errors=[];try{items=await fetchRSS(FJ_RSS,{Referer:'https://www.financialjuice.com/home'})}catch(e){errors.push('FinancialJuice: '+String(e.message||e))}const reutersUrl=process.env.REUTERS_RSS_URL,reutersToken=process.env.REUTERS_TOKEN;if(reutersUrl){try{reuters=await fetchRSS(reutersUrl,reutersToken?{Authorization:`Bearer ${reutersToken}`}:{})}catch(e){errors.push('Reuters: '+String(e.message||e))}}let macroUpdates=items.filter(x=>x.macro).map(x=>({...x.macro,headline:x.title,link:x.link}));return res.status(200).json({mode:items.length?'live':'degraded',financialJuiceLive:!!items.length,generatedAt:new Date().toISOString(),items,financialjuice:items,macroUpdates,reuters,reutersConfigured:!!reutersUrl,errors});}
